const _BASE = "HOME/";

export const CHANGE_WRITER_LIST = `${_BASE}CHANGE_WRITER_LIST`;

export const CHANGE_WRITER_PAGE = `${_BASE}CHANGE_WRITER_PAGE`;

export const SET_ARTICLE_LIST = `${_BASE}SET_ARTICLE_LIST`;

export const SET_SCROLL_SHOW = `${_BASE}SET_SCROLL_SHOW`;
